### ISSUE TITLE
2sxc Blog app search only index page 1

### ISSUE THREAD

**Issue by imhobie** [2sic/app-blog#5]
Using 2sxc Blog app, the DNN only indexes whatever is on first page of Blog page.

Second page onwards is not indexed, hence doesn't show in search results.

[http://stackoverflow.com/questions/40445748/2sxc-blog-app-search-only-index-page-1](url)

**Comment by iJungleboy** [comment]
Note that we won't be able to fix this on short notice, because we never use the DNN search and always prefer google. 

BUT: It should be fairly easy to change this yourself, because 2sxc can customize everything it gives to the search. Here are the steps you want to do:
1. In the query that delivers data to the template, you want to add another stream which delivers all items instead of just the paged ones. For this, drag the out of the valuesort (before thepaging) to the cache and name it "SearchIndex", then drag another from the cache to the final target, name both the cache-out and the target-in "SearchIndex"
2. In the template, add a section which optimizes for the search index

Here's some help

https://github.com/2sic/2sxc/wiki/Razor-SexyContentWebPage.CustomizeSearch

https://github.com/2sic/2sxc/wiki/Razor-SexyContentWebPage.CustomizeData

See solution posted here http://stackoverflow.com/questions/39894301/2sxc-blog-app-posts-and-dnn-search

**Comment by imhobie** [comment]
![searchindex](https://cloud.githubusercontent.com/assets/235668/20254262/c333759a-aa43-11e6-870a-1efb21c8b29d.PNG)

Thanks, the change in the the visual query now gets me all page items in search results., but **where exactly to add the  **SearchIndex** in the template code**, because now all items in the search result are missing the post query string from them, so the results show like:
/blog/i-am-a-post-title
rather than 
/blog/post/i-am-a-post-title

```
@functions{

    // Prepare the data - get all categories through the pipeline

    public override void CustomizeData()
    {

    }

    /// <summary>

    /// Populate the search - ensure that each entity has an own url/page

    /// </summary>

    /// <param name="searchInfos"></param>

    /// <param name="moduleInfo"></param>

    /// <param name="startDate"></param>

    public override void CustomizeSearch(Dictionary<string, List<ISearchInfo>> searchInfos, ModuleInfo moduleInfo, DateTime startDate)
    {

         foreach (var si in searchInfos["Default"])
    {
        si.QueryString = "post=" + AsDynamic(si.Entity).UrlKey;
    }
    }
}
```

**Comment by iJungleboy** [comment]
In the main razor file - the list-view.

**Comment by imhobie** [comment]
Awesome, works great. Thanks a lot
